### ISSUE TITLE
Problem with code generation with ApiSession

### ISSUE THREAD

**Issue by zdb999** [dwrensha/sandstorm-rust#3]
The capnp definition for ApiSession is an extension of the WebSession definition. ([This](https://github.com/sandstorm-io/sandstorm/blob/master/src/sandstorm/api-session.capnp#24) is the definition file.) However, the web_session_capnp server functions are missing from the api_session_capnp code. How can this be rectified? Is the best solution to copy the missing functions from the WebSession definition to the ApiSession definition, or should this be addressed with the capnp module?

**Comment by dwrensha** [comment]
When you implement an `api_session::Server`, you must also implement `web_session::Server`, because of this trait bound in the generated code:

```rust
pub mod api_session {
 pub trait Server<> : crate::web_session_capnp::web_session::Server  {}
}
```

If you have an `api_session::Client` and you want to call `web_session::Client` methods on it, you first need to upcast it to a `web_session::Client`.  Unfortunately, upcasting in capnp-rpc-rust is manual and clunky at the moment. You need to do something like:

```rust
let web_session_client = web_session::Client { client: api_session_client.client };
```

**Comment by zdb999** [comment]
Ok, that makes sense. So that's what the "upcasting" in raw API example is doing. Thanks for the explanation.
